name:                tvschedule
version:             0.1.0.0
github:              "tcallan/tvschedule"
license:             BSD3
author:              "tcallan"
maintainer:          "example@example.com"
copyright:           "2022 tcallan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tcallan/tvschedule#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wnoncanonical-monad-instances

default-extensions:
- DeriveGeneric
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- req
- aeson
- aeson-casing
- text
- bytestring
- time
- containers
- blaze-html
- dhall

library:
  source-dirs: src

executables:
  tvschedule-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tvschedule
    - optparse-applicative

tests:
  tvschedule-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tvschedule
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-instances
